### ISSUE TITLE
Toggles and Panels/Tabs

### ISSUE THREAD

**Issue by saracase** [saracase/dsn1676-term-project-1#2]
I was just wondering if we learned how to create a toggle and panels/tabs? I couldn't find it in the in class assignments we did, although I think for the toggle we use expand/collapse. But I wasn't sure about the panels/tabs

@thomasjbradley

**Comment by thomasjbradley** [comment]
We didn't learn them in class, but there's a video series on it:
https://github.com/algonquindesign/javascript/tree/master/components
