### ISSUE TITLE
SVG not working with js animation

### ISSUE THREAD

**Issue by saracase** [saracase/dsn1676-term-project-1#4]
When the js-active doesn’t seem to be working since I have an opacity on my svg at 0 and my js-active is opacity of 1, so when I scroll down it should change, so the svg becomes visible, but it doesn’t so I;m not sure what’s wrong

@thomasjbradley

**Comment by thomasjbradley** [comment]
Instead of targeting the SVG directly, try wrapping it in a `<div>` and putting the `.js-active` class on it.

**Comment by saracase** [comment]
So I tried that and it didn't work

**Comment by thomasjbradley** [comment]
The Javascript is working properly, I checked with the web inspector.

In the CSS, on this line:
https://github.com/saracase/dsn1676-term-project-1/blob/gh-pages/css/main.css#L439
Is it actually the `.js-active` thing that has an opacity of 0?

**Comment by saracase** [comment]
I'm not sure if I understand what you mean. The .js-active has an opacity of 1 and I had it like that so when I scroll down the svg appears but when I scroll down it doesn't show up

**Comment by thomasjbradley** [comment]
`.js-active` is being applied to the `<div>` that surrounds the SVG, but the SVG also has an `opacity: 0` on it here:
https://github.com/saracase/dsn1676-term-project-1/blob/gh-pages/css/main.css#L371

**Comment by saracase** [comment]
So I moved the .cat-on-yarn tag onto the div rather then the svg but now the svg is not hidden at the beginning

**Comment by thomasjbradley** [comment]
It's invisible for me.

**Comment by saracase** [comment]
I don't think I see the svg animation working for me, is it working for you?

**Comment by thomasjbradley** [comment]
Yep is definitely working for me in Chrome. What browser are you testing in?

**Comment by saracase** [comment]
I tested it in Chrome originally but also tested it in Firefox and Safari

**Comment by thomasjbradley** [comment]
We're talking about the cat rotating on the blue yarn ball, right..?

**Comment by saracase** [comment]
Yep!
